### ISSUE TITLE
Some Bug Reports and Sugestions

### ISSUE THREAD

**Issue by LostUmbrella58** [JoseGamerPT/RealSkywars#22]
As you said RealSkywars currently doesnt support 1.21.4 so okay i switch server-core to the latest 1.21.1 Paper.
First of all, here are my bug reports (not all of them are bugs but at least most of them have serious impact on normal game play) :

Im wondering how many delays do lobby item give 🤔
and permission of /sw maps command is not related to rsw.join (then i found it requires rsw.admin permission in src)
using ItemJoin plugin but in case of disabling all of plugins which could clear player's inventory but RealSkywars' lobby item still wont be given
so does Realskywars give players a complete new inventory instead of giving them lobby items based on their original inventory?
then how can i let players join sw in command😕
and wtf why spectators are visible to in-game players (join as spectators)
they can even lose their hungry bar and unable to fly
and players who died in game will be given creative mode 💀
one more interesting issue:
if you create arenas by typing /sw create <map-name> <type> 12 1
then this arena would be "TEAMS" mode
actually its a solo mode arena but its considered as a Teams Mode arena
now 1 more bug:
players will get fall damage during Invincibility-Seconds
and idk why arena created by 
"/sw create <map-name> default 6 2"
will lead to a 0/24 arena🤔

Here are more suggestions🫡 :
1.Add Per-Arena-Chat and Hide-Playing-Players-from-Tablist (not only me but many servers use TAB plugin)
2.Switch logical of lobby items give
3.Like above said, fix issues related to Spectators 
4.Let Creative players be able to break blocks in RealSkywars protected lobby, otherwise they can only break blocks through /setblock or other ways
5.plz add Hex code support for high server version🙏
6.Allow texts in sign to be translated because they can't be translated in current version of RealSkywars

**Comment by joserodpt** [comment]
"Im wondering how many delays do lobby item give 🤔" what do you mean by this?

**Comment by joserodpt** [comment]
"Switch logical of lobby items give" what do you mean by this?

**Comment by LostUmbrella58** [comment]
> "Im wondering how many delays do lobby item give 🤔" what do you mean by this?

hold on I'll send you a video

**Comment by LostUmbrella58** [comment]
> "Switch logical of lobby items give" what do you mean by this?

https://www.dropbox.com/scl/fi/f0lq0nz3hh63o2xu4gdjs/java-2025-02-01-12-31-50-989.mp4?rlkey=dvg97b3ypcle1qjt00q4gmbp0&st=uxifvr1e&dl=0

**Comment by joserodpt** [comment]
Please test this new build, and report some feedback thanks: 

[RealSkywars.jar.zip](https://github.com/user-attachments/files/18664041/RealSkywars.jar.zip)

**Comment by LostUmbrella58** [comment]
> Please test this new build, and report some feedback thanks:
> 
> [RealSkywars.jar.zip](https://github.com/user-attachments/files/18664041/RealSkywars.jar.zip)

thanks! so i found out RealSkywars' TAB doesnt support placeholders...

**Comment by LostUmbrella58** [comment]
> Please test this new build, and report some feedback thanks:
> 
> [RealSkywars.jar.zip](https://github.com/user-attachments/files/18664041/RealSkywars.jar.zip)

Thank you!
So first issue, chests can be broken without any items inside until players open chests before they open them.
video: 

https://github.com/user-attachments/assets/fa408243-5493-4f17-85e9-3ee1f73751e3

The second is that OP can break blocks before game starts (any blocks, not only the glass cage but the whole maps)

**Comment by LostUmbrella58** [comment]
https://github.com/user-attachments/assets/570e0513-5f6f-49ca-bedc-ef09d6fee988
the second video related to chests

**Comment by LostUmbrella58** [comment]
> Please test this new build, and report some feedback thanks:
> 
> [RealSkywars.jar.zip](https://github.com/user-attachments/files/18664041/RealSkywars.jar.zip)

3. Players who joined as Spectators still can't fly (they joined in a running arena)
4. Spectators who died to become are still in Creative Mode

**Comment by LostUmbrella58** [comment]
https://github.com/user-attachments/assets/64f66ec0-e70c-4618-81c8-8d0c44f42a8a

OP is allowed to break blocks before game starts video

**Comment by LostUmbrella58** [comment]
> > Please test this new build, and report some feedback thanks:
> > [RealSkywars.jar.zip](https://github.com/user-attachments/files/18664041/RealSkywars.jar.zip)
> 
> 3. Players who joined as Spectators still can't fly (they joined in a running arena)
> 4. Spectators who died to become are still in Creative Mode

5. You can take items out from and into an arena 

https://github.com/user-attachments/assets/443b9a2a-1cf4-45dd-8be4-ccff4b8a93d5

https://github.com/user-attachments/assets/b72d581e-0ff0-4c02-a56c-eb853d594dba

**Comment by LostUmbrella58** [comment]
![Image](https://github.com/user-attachments/assets/90dc9e8a-25da-467b-b21e-f0fdf0dad6d0)
6.IDK why but a player can rarely see armor stands instead of displaying clock

**Comment by LostUmbrella58** [comment]
> Please test this new build, and report some feedback thanks:
> 
> [RealSkywars.jar.zip](https://github.com/user-attachments/files/18664041/RealSkywars.jar.zip)

So above all, here are newly found issues (some of them might be newly in this dev build):

- [x] 1.Chests can be broken without any items inside until players open chests before they open them. (Many players prefer breaking chests to grabbing items from chests so it might make that kind of players confused)
- [x] 2.OP can break blocks before game starts (any blocks, not only the glass cage but the whole maps)
- [ ] 3.Players who joined as Spectators still can't fly (they joined in a running arena)
- [ ] 4.Spectators who died to become are still in Creative Mode
- [x] 5.You can take items out from and into an arena
- [x] 6.IDK why but a player can rarely see armor stands instead of displaying clock.
- [x] 7.Players can lose their hunger bar during waiting period 

And further suggestions:
- [ ] 1.Allow spectators who join in a running arena to spectate to be able to fly
- [ ] 2.Give spectators who died from a running arena the similar spectate pattern like suggestion point 1

I really appreciate your skywars plugins, 🫡

**Comment by joserodpt** [comment]
Could not reproduce bug 3, 4, 5. Video?
Bug 6 can be related to server / hologram plugin / if you're using geyser/other version compatibility plugin.
Could not reproduce suggestion 1 and 2. Video?

**Comment by LostUmbrella58** [comment]
> > > Please test this new build, and report some feedback thanks:
> > > [RealSkywars.jar.zip](https://github.com/user-attachments/files/18664041/RealSkywars.jar.zip)
> > 
> > 
> > 
> > 3. Players who joined as Spectators still can't fly (they joined in a running arena)
> > 4. Spectators who died to become are still in Creative Mode
> 
> 5. You can take items out from and into an arena
> 
>  java.2025-02-05.18-45-23-559.mp4 
>  java.2025-02-05.18-45-51-552.mp4

here is BUG 5 video

**Comment by LostUmbrella58** [comment]
> Could not reproduce bug 3, 4, 5. Video? Bug 6 can be related to server / hologram plugin / if you're using geyser/other version compatibility plugin. Could not reproduce suggestion 1 and 2. Video?

https://github.com/user-attachments/assets/2144b7d6-3f1e-4ae4-9fb8-7e02d2666fd8

Bug 3

**Comment by LostUmbrella58** [comment]
https://github.com/user-attachments/assets/13acd274-4947-4b24-af78-373904ba6d67
btw OP can also break blocks as spectators

**Comment by LostUmbrella58** [comment]
> Could not reproduce bug 3, 4, 5. Video? Bug 6 can be related to server / hologram plugin / if you're using geyser/other version compatibility plugin. Could not reproduce suggestion 1 and 2. Video?

https://github.com/user-attachments/assets/90746d82-4cd7-459f-a71b-a6b8b9956245

ok so i double checked your in dev build
Bug 4 isnt Creative Mode but they cant fly

**Comment by joserodpt** [comment]
> > Could not reproduce bug 3, 4, 5. Video? Bug 6 can be related to server / hologram plugin / if you're using geyser/other version compatibility plugin. Could not reproduce suggestion 1 and 2. Video?
> 
>  java.2025-02-06.12-28-28-621.mp4 
> 
> Bug 3

players in spectator should be in creative mode, the plugin set's the player to creative automatically. another plugin can change that

**Comment by joserodpt** [comment]
Please test this new build, the other issues have been fixed, please give me feedback, thanks!

[RealSkywars.jar.zip](https://github.com/user-attachments/files/18688850/RealSkywars.jar.zip)

**Comment by LostUmbrella58** [comment]
https://github.com/user-attachments/assets/f3f69426-2f13-4a71-b465-878d7bd8735b
Spectators still can't fly

**Comment by LostUmbrella58** [comment]
https://github.com/user-attachments/assets/fe5ebf72-08fc-4b80-9744-a2e3f47feda0

"players will get fall damage during Invincibility-Seconds"

**Comment by LostUmbrella58** [comment]
So here are new bug reports and suggestions
Bug Reports:

- [ ] 1.Spectators still can't fly (Related to Point 3)
https://github.com/user-attachments/assets/f3f69426-2f13-4a71-b465-878d7bd8735b
- [ ] 2.Players will get fall damage during Invincibility-Seconds (Seems like in Team Mode it wont work)
https://github.com/user-attachments/assets/3be637c7-b9a7-4e81-b145-b9e85c16554f
- [x] 3.Spectators can kill mobs and sometimes some players wont be given Creative Mode and I personally think it's not a wise decision to choose this spectate pattern. And those non-Creative Mode players will still lose their food level
https://github.com/user-attachments/assets/614d1995-947a-435c-af7b-8a3be5bb0c41
https://github.com/user-attachments/assets/9e65166e-b0a7-44bf-a431-ce579f63ca97
- [x] 4.Spectators can break farmlands
https://github.com/user-attachments/assets/66e93b10-2eaf-48b2-82fe-dc07215e3b7e
- [ ] 5.Borders seems wont shrink even in deathmatch
https://github.com/user-attachments/assets/8c607926-94e2-47a9-94da-5b0e68704f80

Suggestions:
- [x] 1.It's a little hard to figure out who is your teammate in Team Mode
https://github.com/user-attachments/assets/944a8999-50f3-4c7f-866e-422502162d34

By the way, I've already set
`Invincibility-Seconds: 5
  Enable-Tab-Formatting: true
  Enable-Chat-Per-Map: true`

**Comment by LostUmbrella58** [comment]
New Bug Report:
- [ ] 6.Game already Started but countdown stuck and PVP isnt enabled
https://github.com/user-attachments/assets/838d4ff9-2d9b-4307-85d7-265abb484779
here is the full video about this round
https://www.dropbox.com/scl/fi/ywlv6pl8wy8mxmlf6apcv/java-2025-02-06-21-44-18-923.mp4?rlkey=lrpccr276u2mrflaybbcvn9dz&st=hv9d7w7e&dl=0

and here is error log
`[21:49:51 WARN]: [RealSkywars] Task #25967 for RealSkywars v1.2 generated an exception
java.lang.NullPointerException: Cannot invoke "joserodpt.realskywars.api.utils.CountdownTimer.getPassedSeconds()" because "this.mapTimer" is null
        at RealSkywars.jar/joserodpt.realskywars.api.map.RSWMap.lambda$sendLog$5(RSWMap.java:645) ~[RealSkywars.jar:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597) ~[?:?]
        at RealSkywars.jar/joserodpt.realskywars.api.map.RSWMap.sendLog(RSWMap.java:645) ~[RealSkywars.jar:?]
        at RealSkywars.jar/joserodpt.realskywars.api.map.RSWMap.spectate(RSWMap.java:447) ~[RealSkywars.jar:?]
        at RealSkywars.jar/joserodpt.realskywars.plugin.listeners.PlayerListener.lambda$onEntityDamage$2(PlayerListener.java:443) ~[RealSkywars.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]`

**Comment by joserodpt** [comment]
Could not reproduce issues 1,2,3.
Issue 4 is fixed and issue " little hard to figure out who is your teammate in Team Mode" will be implemented. 
Issue 6 seems to be something broken. Could you re-make the server, clear all old configs and configure  from the start?

**Comment by LostUmbrella58** [comment]
Issue 2 is related to Team Modes, you can find your teammates get damaged on game starts
Issue 1 is related to "join in a running arena as a Spectator"
I'll double check Issue 3 and regenerate full config

**Comment by LostUmbrella58** [comment]
![Image](https://github.com/user-attachments/assets/bc29bdcf-8883-420e-8c42-2f31216aea0a)
yeah so i double checked again and again, it does like what i said as quoted message.
and idk why one of my players reported he accidentally picked up an arrow

> Issue 2 is related to Team Modes, you can find your teammates get damaged on game starts Issue 1 is related to "join in a running arena as a Spectator" I'll double check Issue 3 and regenerate full config

**Comment by LostUmbrella58** [comment]
![Image](https://github.com/user-attachments/assets/9d315eac-6081-4505-bc5d-a747a9a41def)
oh, sorry, actually it is "Spectators can pick up projectiles"

**Comment by LostUmbrella58** [comment]
https://github.com/user-attachments/assets/10dd856d-e37f-46f1-b256-6bb891e7d79e
7. Spectators (tested in case of "died as Spectators") can pick up projectiles

**Comment by LostUmbrella58** [comment]
> Could not reproduce issues 1,2,3. Issue 4 is fixed and issue " little hard to figure out who is your teammate in Team Mode" will be implemented. Issue 6 seems to be something broken. Could you re-make the server, clear all old configs and configure from the start?

magika:
  Settings:
    Max-Game-Time: 500
    Invincibility-Seconds: 5
    Time-End-Game: 10
    Time-To-Start: 30
    Unregistered: false
    DisplayName: 双人-宫殿
    GameType: TEAMS
    Spectator: true
    Instant-End: false
    Ranked: false
    Border: true
  Locations:
    Cages:
      '3':
        X: 60
        Y: 89
        Z: 4
      '6':
        X: -62
        Y: 89
        Z: 4
      '4':
        X: 31
        Y: 89
        Z: 52
      '1':
        X: -29
        Y: 89
        Z: -52
      '2':
        X: 27
        Y: 89
        Z: -52
      '5':
        X: -33
        Y: 89
        Z: 52
    Spectator:
      X: 51.0
      Y: 60.0
      Z: 1.0
      Yaw: 0.0
      Pitch: 0.0
  World:
    Border:
      POS1-X: -117.0
      POS1-Y: -64.0
      POS1-Z: -78.0
      POS2-X: 132.0
      POS2-Y: 319.0
      POS2-Z: 78.0
  world: magika
  name: magika
  type: DEFAULT
  number-of-players: 24

this arena should be 2 players per team but result in 4 players per team, and everyone died by fallen damage during Invincibility-Seconds

**Comment by joserodpt** [comment]
Please test the below .jar file to test the latest fixes:

[RealSkywars.jar.zip](https://github.com/user-attachments/files/18786665/RealSkywars.jar.zip)

**Comment by LostUmbrella58** [comment]
thanks! However, I deleted all of existing maps and re-created new maps in your dev build, found that players who joined sw game after game started were still Survival Mode and they still couldnt fly...
And in team mode, only 1 player in a team won't get fall damage during Invincibility seconds.
Server is using the latest 1.21.1 Paper

**Comment by joserodpt** [comment]
[RealSkywars.jar.zip](https://github.com/user-attachments/files/18815825/RealSkywars.jar.zip)
Fixed more issues that you created, please check them out, thanks!

**Comment by LostUmbrella58** [comment]
hmmm... Unfortunately your teammates will get damaged during invincibility seconds....
that issue seems to still exist
